#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# This wizard handles a GitHub App private key. Nothing is persisted to disk, so
# the library's .env upsert is pointed at /dev/null and write_env is never called.
ENV_FILE="/dev/null"

# Repos that need the App credentials. shared_workflow runs Renovate; shared_scripts
# runs release-please. Both mint tokens from the same App.
TARGET_REPOS=(ekawijayasusilo/shared_workflow ekawijayasusilo/shared_scripts)

# The library's set_secret/set_var write to the current directory's repo. This
# wizard writes to two named remote repos instead.
set_var_in() {
  if gh variable set "$2" --repo "$1" --body "$3" >/dev/null 2>&1; then
    printf '  %s✓ set%s variable %s on %s\n' "$GREEN" "$RESET" "$2" "$1"
  else
    SKIPPED+=("variable $2 on $1")
    warn "failed to set variable $2 on $1"
  fi
}

set_secret_from_file() {
  if gh secret set "$2" --repo "$1" < "$3" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$2 ($1)")
    printf '  %s✓ set%s secret %s on %s\n' "$GREEN" "$RESET" "$2" "$1"
  else
    SKIPPED+=("secret $2 on $1")
    warn "failed to set secret $2 on $1"
  fi
}

# Strip surrounding quotes and expand a leading ~ — both show up when a path is
# dragged into the terminal.
normalize_path() {
  local p="$1"
  p="${p%\"}"; p="${p#\"}"
  p="${p%\'}"; p="${p#\'}"
  printf '%s' "${p/#\~/$HOME}"
}

# The library's finish() reads empty arrays, which is an unbound-variable error
# under `set -u` on bash 3.2 (still the default /bin/bash on macOS).
if (( BASH_VERSINFO[0] < 4 )); then
  printf 'This wizard needs bash 4 or newer (found %s).\n' "${BASH_VERSION}" >&2
  printf 'On macOS: brew install bash, then run it with that bash.\n' >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  printf 'The GitHub CLI (gh) must be installed and authenticated.\n' >&2
  printf 'Install: https://cli.github.com  then run: gh auth login\n' >&2
  exit 1
fi

banner "Owner bootstrap — automation GitHub App"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the automation GitHub App"
say "This runs ONCE EVER for your GitHub account. It creates one App that both"
say "Renovate and release-please mint short-lived tokens from."
note "If you have already done this, stop now — you want scripts/setup-repo.sh instead."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: something identifiable, e.g. '<your-handle>-automation'."
step "Homepage URL: your GitHub profile URL is fine."
step "Under 'Webhook', UNCHECK 'Active'. This App is never called back."
step "Repository permissions — set exactly these:"
note "    Contents:      Read and write"
note "    Pull requests: Read and write"
note "    Issues:        Read and write"
note "    Workflows:     Read and write   (lets Renovate bump pinned action SHAs)"
note "    Metadata:      Read-only        (selected automatically)"
step "'Where can this GitHub App be installed?' — Only on this account."
step "Click 'Create GitHub App'."
ask APP_ID "Paste the App ID shown at the top of the page:"
say "The page URL is now https://github.com/settings/apps/<slug>"
ask APP_SLUG "Paste that <slug>:"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Generate and capture the private key"
open_url "https://github.com/settings/apps/${APP_SLUG}#private-key"
step "Scroll to 'Private keys' and click 'Generate a private key'."
step "Your browser downloads a .pem file — usually to ~/Downloads."
warn "This is the only copy. GitHub will not show it again."
KEY_PATH=""
key_attempts=0
while [[ ! -f "$KEY_PATH" ]]; do
  # Bounded: on EOF (piped stdin) `ask` returns empty forever.
  if (( key_attempts >= 5 )); then
    warn "Gave up after 5 attempts. Re-run once you know the path."
    exit 1
  fi
  key_attempts=$((key_attempts + 1))
  ask KEY_PATH_RAW "Full path to the downloaded .pem file:"
  KEY_PATH=$(normalize_path "$KEY_PATH_RAW")
  [[ -f "$KEY_PATH" ]] || warn "No file at: $KEY_PATH"
done
if ! grep -q "BEGIN RSA PRIVATE KEY" "$KEY_PATH"; then
  warn "That file does not look like a PEM private key. Continuing anyway."
fi
say "Read $(wc -c < "$KEY_PATH" | tr -d ' ') bytes."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Install the App on your repositories"
open_url "https://github.com/settings/apps/${APP_SLUG}/installations"
step "Click 'Install' next to your account."
step "Choose 'Only select repositories' and select AT LEAST:"
for repo in "${TARGET_REPOS[@]}"; do note "    ${repo##*/}"; done
step "Add every project repo that will use Renovate or release-please."
note "You can come back to this page any time to add more repos."
pause "Press Enter once the App is installed."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Write the credentials to GitHub"
say "Writing RENOVATE_APP_ID (variable) and RENOVATE_APP_PRIVATE_KEY (secret)."
for repo in "${TARGET_REPOS[@]}"; do
  set_var_in "$repo" RENOVATE_APP_ID "$APP_ID"
  set_secret_from_file "$repo" RENOVATE_APP_PRIVATE_KEY "$KEY_PATH"
done
printf '\n'
say "The key now lives in GitHub secrets. The downloaded copy is the weakest link."
if confirm "Delete $KEY_PATH now?"; then
  if command -v shred >/dev/null 2>&1; then shred -u "$KEY_PATH"; else rm -f "$KEY_PATH"; fi
  say "Deleted."
else
  warn "Left in place. Store it somewhere safe or delete it by hand."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify"
for repo in "${TARGET_REPOS[@]}"; do
  say "$repo"
  note "  variables: $(gh variable list --repo "$repo" --json name -q '[.[].name]|join(", ")' 2>/dev/null || echo '(unreadable)')"
  note "  secrets:   $(gh secret   list --repo "$repo" --json name -q '[.[].name]|join(", ")' 2>/dev/null || echo '(unreadable)')"
done
printf '\n'
say "Next: for each new project repo, run scripts/setup-repo.sh from that repo."
pause "Press Enter to finish."

finish
