#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# This wizard writes only to GitHub. Nothing is persisted to disk, so the
# library's .env upsert is pointed at /dev/null and write_env is never called.
ENV_FILE="/dev/null"

REPO=""            # OWNER/REPO, resolved and confirmed in stage 1
DEFAULT_BRANCH=""
PHASE=""

# The library's finish() reads empty arrays, which is an unbound-variable error
# under `set -u` on bash 3.2 (still the default /bin/bash on macOS).
if (( BASH_VERSINFO[0] < 4 )); then
  printf 'This wizard needs bash 4 or newer (found %s).\n' "${BASH_VERSION}" >&2
  printf 'On macOS: brew install bash, then run it with that bash.\n' >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  printf 'The GitHub CLI (gh) must be installed and authenticated.\n' >&2
  printf 'Install: https://cli.github.com  then run: gh auth login\n' >&2
  exit 1
fi

# ── helpers ───────────────────────────────────────────────────────────────

# Resumability comes from probing live GitHub state, not from a local file.
has_secret() { gh secret   list --repo "$REPO" --json name -q '.[].name' 2>/dev/null | grep -qx "$1"; }
has_var()    { gh variable list --repo "$REPO" --json name -q '.[].name' 2>/dev/null | grep -qx "$1"; }

set_repo_secret() {
  if gh secret set "$1" --repo "$REPO" --body "$2" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$1")
    printf '  %s✓ set%s secret %s\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("secret $1"); warn "failed to set secret $1"
  fi
}

set_repo_var() {
  if gh variable set "$1" --repo "$REPO" --body "$2" >/dev/null 2>&1; then
    printf '  %s✓ set%s variable %s\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("variable $1"); warn "failed to set variable $1"
  fi
}

# JSON string array, without depending on jq being installed.
json_array() {
  local out="" item
  for item in "$@"; do
    item=${item//\\/\\\\}; item=${item//\"/\\\"}
    out+="\"$item\","
  done
  printf '[%s]' "${out%,}"
}

usage() { printf 'Usage: bash setup-repo.sh [--repo OWNER/REPO]\n'; exit 0; }

REPO_ARG=""
while (( $# )); do
  case "$1" in
    --repo) REPO_ARG="${2:-}"; shift 2 ;;
    -h|--help) usage ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; exit 1 ;;
  esac
done

# ── pre-flight: resolve (read-only) and detect phase ──────────────────────
# Nothing here mutates anything. The human confirms the repo in stage 1, which
# still runs before the first write.

if [[ -n "$REPO_ARG" ]]; then
  REPO="$REPO_ARG"
else
  REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)
fi
if [[ -z "$REPO" ]]; then
  printf 'Could not determine the target repository.\n' >&2
  printf 'Run this from inside a repo checkout, or pass --repo OWNER/REPO.\n' >&2
  exit 1
fi

# `gh api` writes its error BODY to stdout on a non-2xx response, so a bare
# `$(... || echo 0)` captures that JSON too. Everything numeric goes through this.
num_or_zero() { [[ "$1" =~ ^[0-9]+$ ]] && printf '%s' "$1" || printf '0'; }

DEFAULT_BRANCH=$(gh repo view "$REPO" --json defaultBranchRef -q .defaultBranchRef.name 2>/dev/null) || DEFAULT_BRANCH=""
[[ "$DEFAULT_BRANCH" =~ ^[A-Za-z0-9._/-]+$ ]] || DEFAULT_BRANCH="main"

protected_checks=$(gh api "repos/$REPO/branches/$DEFAULT_BRANCH/protection" \
  --jq '(.required_status_checks.contexts // []) | length' 2>/dev/null) || protected_checks=0
protected_checks=$(num_or_zero "$protected_checks")

successful_runs=$(gh run list --repo "$REPO" --status success --limit 1 --json databaseId -q 'length' 2>/dev/null) || successful_runs=0
successful_runs=$(num_or_zero "$successful_runs")

if (( protected_checks > 0 )); then
  PHASE="done"; TOTAL_STAGES=1
elif (( successful_runs > 0 )); then
  PHASE="2"; TOTAL_STAGES=4
else
  PHASE="1"; TOTAL_STAGES=9
fi

banner "Repo onboarding — phase ${PHASE}"

# ── 1 ─ runs in both phases ───────────────────────────────────────────────
# Hard requirement: confirm the target before ANY change. This wizard mutates
# repo settings and secrets; acting on the wrong repo is costly and silent.
stage "Resolve and confirm the target repository"
printf '\n'
printf '      %s%s%s%s\n' "$BOLD" "$YELLOW" "$REPO" "$RESET"
printf '      %sdefault branch: %s%s\n\n' "$DIM" "$DEFAULT_BRANCH" "$RESET"
say "Everything after this point writes secrets, variables and settings to that repo."
if ! confirm "Is that the correct repository?"; then
  printf '\n'; warn "Aborted. Re-run with: bash setup-repo.sh --repo OWNER/REPO"
  exit 1
fi

if [[ "$PHASE" == "done" ]]; then
  _clear
  printf '\n%s%s  Nothing to do%s\n\n' "$BOLD" "$GREEN" "$RESET"
  note "$REPO already has branch protection with required checks on $DEFAULT_BRANCH."
  note "secrets:   $(gh secret   list --repo "$REPO" --json name -q '[.[].name]|join(", ")' 2>/dev/null || echo '(unreadable)')"
  note "variables: $(gh variable list --repo "$REPO" --json name -q '[.[].name]|join(", ")' 2>/dev/null || echo '(unreadable)')"
  printf '\n'
  exit 0
fi

OWNER="${REPO%%/*}"
NAME="${REPO##*/}"

if [[ "$PHASE" == "1" ]]; then

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Verify the automation GitHub App is installed here"
if gh api "repos/$REPO/installation" >/dev/null 2>&1; then
  say "The automation App is installed on $REPO."
else
  warn "No GitHub App installation found on $REPO."
  printf '\n'
  say "This wizard never creates an App and never writes a private key."
  say "That is a one-time, account-wide job. Run the owner bootstrap first:"
  note "  curl -fsSL -o bootstrap-owner.sh \\"
  note "    https://raw.githubusercontent.com/ekawijayasusilo/shared_scripts/v1.1.0/scripts/bootstrap-owner.sh" # x-release-please-version
  note "  less bootstrap-owner.sh"
  note "  bash bootstrap-owner.sh"
  printf '\n'
  say "If the App already exists, just add this repo to its installation:"
  open_url "https://github.com/settings/installations"
  exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Codecov"
if has_secret CODECOV_TOKEN; then
  say "CODECOV_TOKEN is already set — skipping."
else
  say "Coverage produced by CI is uploaded to Codecov."
  open_url "https://github.com/apps/codecov/installations/new"
  step "Install the Codecov app and grant it access to $NAME."
  pause "Press Enter once Codecov can see the repo."
  open_url "https://app.codecov.io/gh/${OWNER}/${NAME}/config/general"
  step "Copy the repository upload token."
  ask_secret CODECOV_TOKEN "Paste the Codecov upload token:"
  if [[ -n "$CODECOV_TOKEN" ]]; then
    set_repo_secret CODECOV_TOKEN "$CODECOV_TOKEN"
  else
    SKIPPED+=("secret CODECOV_TOKEN"); warn "blank — skipped"
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "OpenCode API key"
if has_secret OPENCODE_API_KEY; then
  say "OPENCODE_API_KEY is already set — skipping."
else
  say "Used by the ocr-review, opencode and opencode-simplify reusable workflows."
  open_url "https://opencode.ai/auth"
  step "Sign in and copy an API key."
  ask_secret OPENCODE_API_KEY "Paste the OpenCode API key:"
  if [[ -n "$OPENCODE_API_KEY" ]]; then
    set_repo_secret OPENCODE_API_KEY "$OPENCODE_API_KEY"
  else
    SKIPPED+=("secret OPENCODE_API_KEY"); warn "blank — skipped"
  fi
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Optional LLM overrides for the PR reviewer"
say "Leave both blank to use the reusable workflow's defaults."
ask OCR_LLM_URL   "OCR_LLM_URL   (blank to skip):"
ask OCR_LLM_MODEL "OCR_LLM_MODEL (blank to skip):"
[[ -n "$OCR_LLM_URL"   ]] && set_repo_var OCR_LLM_URL   "$OCR_LLM_URL"
[[ -n "$OCR_LLM_MODEL" ]] && set_repo_var OCR_LLM_MODEL "$OCR_LLM_MODEL"
[[ -z "${OCR_LLM_URL}${OCR_LLM_MODEL}" ]] && note "both blank — nothing written"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Enable Issues"
say "Renovate posts its dependency dashboard as an issue. With Issues disabled"
say "the dashboard silently never appears."
if gh api -X PATCH "repos/$REPO" -F has_issues=true >/dev/null 2>&1; then
  printf '  %s✓%s Issues enabled\n' "$GREEN" "$RESET"
else
  SKIPPED+=("enable Issues"); warn "could not enable Issues"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Actions and merge settings"
open_url "https://github.com/${REPO}/settings/actions"
say "Three settings, all applied for you below:"
note "  Allow auto-merge          — Renovate automerge degrades to nothing without it"
note "  Workflow permissions: RW  — the assistant workflows need contents: write"
note "  Actions may create PRs    — release-please opens its release PR this way"
if gh api -X PATCH "repos/$REPO" -F allow_auto_merge=true >/dev/null 2>&1; then
  printf '  %s✓%s auto-merge allowed\n' "$GREEN" "$RESET"
else
  SKIPPED+=("allow auto-merge"); warn "could not enable auto-merge"
fi
if gh api -X PUT "repos/$REPO/actions/permissions/workflow" \
     -F default_workflow_permissions=write \
     -F can_approve_pull_request_reviews=true >/dev/null 2>&1; then
  printf '  %s✓%s workflow permissions read+write, Actions may create PRs\n' "$GREEN" "$RESET"
else
  SKIPPED+=("Actions workflow permissions"); warn "could not set workflow permissions"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Code scanning"
scanning_state=$(gh api "repos/$REPO/code-scanning/default-setup" --jq '.state' 2>/dev/null || echo "unknown")
if [[ "$scanning_state" == "configured" ]]; then
  say "CodeQL default setup is already configured."
else
  say "Current state: $scanning_state"
  open_url "https://github.com/${REPO}/settings/security_analysis"
  step "Under 'Code scanning', click Set up, choose Default, and enable it."
  note "On public repos this is usually already on."
  pause "Press Enter once you have checked it."
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Stop here — CI must run once"
printf '\n'
say "Phase 1 is done. Required-check NAMES do not exist until the workflows have"
say "actually run, so branch protection cannot be configured yet."
printf '\n'
step "Open a pull request against $DEFAULT_BRANCH."
step "Wait for CI to go green."
step "Re-run this script — it picks up at phase 2 on its own."
printf '\n'
note "  bash setup-repo.sh --repo $REPO"
printf '\n'
pause "Press Enter to finish."

else

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Discover the actual check names"
say "Reading the checks that really ran on $DEFAULT_BRANCH."
CHECKS=()
while IFS= read -r line; do
  [[ -n "$line" ]] && CHECKS+=("$line")
done < <(
  {
    gh api "repos/$REPO/commits/$DEFAULT_BRANCH/check-runs" --jq '.check_runs[].name' 2>/dev/null || true
    gh api "repos/$REPO/commits/$DEFAULT_BRANCH/status"     --jq '.statuses[].context' 2>/dev/null || true
  } | sort -u
)
if (( ${#CHECKS[@]} == 0 )); then
  warn "No checks found on $DEFAULT_BRANCH yet."
  say "Let a PR merge or a push build complete, then re-run."
  exit 1
fi
printf '\n'
for i in "${!CHECKS[@]}"; do
  printf '  %s%2d%s  %s\n' "$BLUE" "$((i+1))" "$RESET" "${CHECKS[$i]}"
done
printf '\n'
ask CHECK_PICK "Which to require? Type all, or numbers like 1 3 4:"
SELECTED=()
if [[ -z "$CHECK_PICK" || "$CHECK_PICK" == "all" ]]; then
  SELECTED=("${CHECKS[@]}")
else
  for n in $CHECK_PICK; do
    if [[ "$n" =~ ^[0-9]+$ ]] && (( n >= 1 && n <= ${#CHECKS[@]} )); then
      SELECTED+=("${CHECKS[$((n-1))]}")
    fi
  done
fi
if (( ${#SELECTED[@]} == 0 )); then
  warn "Nothing selected."; exit 1
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Configure branch protection"
say "About to protect '$DEFAULT_BRANCH' on $REPO with these required checks:"
printf '\n'
for c in "${SELECTED[@]}"; do note "  - $c"; done
printf '\n'
note "Also: linear history, no force pushes, no deletions, pull request required"
note "with 0 approvals — you are the only reviewer and Renovate must automerge."
warn "This restricts direct pushes to $DEFAULT_BRANCH. Admins can still bypass."
if ! confirm "Apply this branch protection?"; then
  warn "Skipped. Re-run when ready."
  exit 0
fi
CONTEXTS=$(json_array "${SELECTED[@]}")
PROTECTION_BODY=$(cat <<JSON
{
  "required_status_checks": { "strict": true, "contexts": ${CONTEXTS} },
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "required_approving_review_count": 0,
    "dismiss_stale_reviews": true
  },
  "restrictions": null,
  "required_linear_history": true,
  "allow_force_pushes": false,
  "allow_deletions": false
}
JSON
)
if printf '%s' "$PROTECTION_BODY" | gh api -X PUT "repos/$REPO/branches/$DEFAULT_BRANCH/protection" --input - >/dev/null 2>&1; then
  printf '  %s✓%s branch protection applied\n' "$GREEN" "$RESET"
else
  SKIPPED+=("branch protection on $DEFAULT_BRANCH")
  warn "Could not apply branch protection."
  note "Branch protection needs a public repo or GitHub Pro/Team. On a private free"
  note "repo, configure a repository ruleset instead:"
  open_url "https://github.com/${REPO}/settings/rules"
  pause "Press Enter to continue."
fi

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Verify"
say "$REPO"
note "  protected checks: $(gh api "repos/$REPO/branches/$DEFAULT_BRANCH/protection" --jq '[.required_status_checks.contexts[]?]|join(", ")' 2>/dev/null || echo '(none)')"
note "  secrets:          $(gh secret   list --repo "$REPO" --json name -q '[.[].name]|join(", ")' 2>/dev/null || echo '(none)')"
note "  variables:        $(gh variable list --repo "$REPO" --json name -q '[.[].name]|join(", ")' 2>/dev/null || echo '(none)')"
note "  issues:           $(gh api "repos/$REPO" --jq '.has_issues' 2>/dev/null || echo '?')"
note "  auto-merge:       $(gh api "repos/$REPO" --jq '.allow_auto_merge' 2>/dev/null || echo '?')"
printf '\n'
pause "Press Enter to finish."

fi

finish
